name: 'Set build sentry'
description: 'Set the sentry that indicates that a build with the current commit has already been completed'
runs:
  using: "composite"
  steps:
    - id: file
      run: echo ::set-output name=file::"$(cd ${{ github.workspace }} && cd .. && pwd)/sentry"
      shell: bash
    - run: echo ${{ github.sha }} > ${{ steps.file.outputs.file }}
      shell: bash
    - uses: actions/upload-artifact@v2
      with:
        name: sentry-${{ github.sha }}
        path: ${{ steps.file.outputs.file }}
