name: 'Set repo information'
description: 'Set github repo and docker hub environment variables'
inputs:
outputs:
  repo_owner:
    description: 'Owner of the github repo, i.e., "Interlisp" in repo "Interlisp/maiko"'
    value: ${{ steps.repo_env.outputs.repo_owner }}
  repo_name:
    description: 'Name of the github repo, i.e., "maiko" in repo "Interlisp/maiko"'
    value: ${{ steps.repo_env.outputs.repo_name }}
  docker_owner:
    description: 'Owner of the docker hub account, i.e., "interlisp" in docker image "interlisp/maiko"'
    value: ${{ steps.repo_env.outputs.docker_owner }}
runs:
  using: "composite"
  steps:
    - id: repo_env
      run: |
        REPO_OWNER=${GITHUB_REPOSITORY%%/*}
        echo "REPO_OWNER=${REPO_OWNER}" >> ${GITHUB_ENV}
        echo ::set-output name=repo_owner::${REPO_OWNER}
        REPO_NAME=${GITHUB_REPOSITORY#*/}
        echo "REPO_NAME=${REPO_NAME}" >> ${GITHUB_ENV}
        echo ::set-output name=repo_name::${REPO_NAME}
        DOCKER_OWNER=$(echo ${REPO_OWNER} | tr '[:upper:]' '[:lower:]')
        echo "DOCKER_OWNER=${DOCKER_OWNER}" >> ${GITHUB_ENV}
        echo ::set-output name=docker_owner::${DOCKER_OWNER}
