name: 'Check build sentry'
description: 'Check for the sentry that indicates that a build with the current commit has already been completed'
outputs:
  release_not_built:
    description: "Set to 'true' is a release with this commit has not been built"
    value: ${{ steps.output.outputs.release_not_built }}
runs:
  using: "composite"
  steps:
    - id: check
      uses: actions/cache@v2.1.7
      with:
        path: ../check-SHA-${{ github.sha }}
        key: check-SHA-${{ github.sha }}
    - id: res
      if: ${{ steps.check.outputs.cache-hit }} == ${{ true }}
      run: echo ::set_output name=no_cache::"false"
      shell: bash
    - id: output
      run: |
        NO_CACHE="${{ steps.res.outputs.no_cache }}";
        if [ "$NO_CACHE" = ""] then NO_CACHE="true"
        if [ "${NO_CACHE}" = "false" ] && [ ! -e ../check-SHA-${{ github.sha }} ] ; \
          then NO_CACHE="true";
        echo ::set-output name=release_not_built::${NO_CACHE}
      shell: bash
