name: 'Check build sentry'
description: 'Check for the sentry that indicates that a build with the current commit has already been completed'
inputs:
  workflow:
    description: "the workflow using the sentry"
    required: true
outputs:
  release_not_built:
    description: "Set to 'true' is a release with this commit has not been built"
    value: ${{ steps.output.outputs.release_not_built }}
runs:
  using: "composite"
  steps:
    - id: get_sentry
      continue-on-error: true
      uses: dawidd6/action-download-artifact@v2.16.0
      with:
        workflow: ${{ inputs.workflow }}
        search_artifacts: true
        name: sentry-${{ github.sha }}
        path: ../sentry
    - id: output
      run: >
        if [ -e ../sentry ]; 
        then echo ::set-output name=release_not_built::false;
        else echo ::set-output name=release_not_built::true;
        fi
      shell: bash
