name: 'Regularize inputs'
description: 'Output either the inputs object or the github.events.inputs'
inputs:
  inputs_obj:
    description: "The inputs object"
    required: true
  github_event_inputs_obj:
    description: "The github.event.inputs object"
    required: true
outputs:
  regularized:
    description: "The regularized inputs as object"
    value: ${{ steps.only.outputs.regularized }}
runs:
  using: "composite"
  steps:
    - id: only
      run: >
        if [ '${{ toJSON(inputs.inputs_obj) }}' = '"null"'  ];
        then echo ::set-output name=regularized::'${{ toJSON(inputs.github_event_inputs_obj) }}'; echo "workflow_dispatch";
        else echo ::set-output name=regularized::'${{ toJSON(inputs.inputs_obj) }}'; echo "workflow_call";
        fi
      shell: bash
